### PR TITLE
Help feature added

### PR DESCRIPTION
**Pull request by dimi-23**
**Fixes issue:**

#24 

**Changes:**

'Help' button added on the main screen, clicking on which opens up a popup like this:

image

### CODE REVIEW

**Comment by AdiChat** [comment]
The design looks good. :+1: 

You may create a post on our [Discourse forum](https://discourse.opengenus.org/) to use it to submit feedback. 
Thereafter, you may place a message along with the link in the help modal. Post title can be "Feedback for Quark" with the "Site feedback" tag.

**Comment by dimi-23** [comment]
I've added the line to give feedbacks in the help modal as suggested by you which solves the issue #24 as well as the issue #29.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by dimi-23** [comment]
Thank you so much! 😄

**Pull request merged**
