### PR TITLE
Fixed Indentation in popup.css

### PR DESCRIPTION
**Pull request by arnavb**
**Fixes issue:** N/A

**Changes:**
- The file `popup.css` was very messy in terms of indentation so I fixed it. 😃 
- I used 4 spaces as the indentation level

### CODE REVIEW

**Comment by wbvhzhvgh** [comment]
حساب دخل 10اعضاء وخود حساب

**Comment by AdiChat** [comment]
Looks good. You need to resolve the minor conflicts before this can be merged. :+1:

**Comment by arnavb** [comment]
@AdiChat I have resolved the merge conflicts! Please merge!

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
