### PR TITLE
results now appear in alphabetical order

### LINKED ISSUE #40: Display Results of Offline Search in Alphabetical Order
**This is a(n):**

- [ ] New feature proposal
- [ ] Reporting a keyword
- [ ] Error
- [ ] Proposal to the Search Engine
- [x] Other

**Details:**

As of now the results of an offline search are visible on the screen in a random order (image attached). A better idea will be to sort these results alphabetically so that it becomes easier for the user to scroll to the desired topic directly rather than by going through all other topics.
im1

### PR DESCRIPTION
**Pull request by Aditi574**
Fixed #40

**Fixes issue:** #40 

**Changes:**
- sorted search keys
- print search results in sorted order

image

### CODE REVIEW

**Comment by Aditi574** [comment]
@AdiChat please review this!

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by AnkitaKhurana** [comment]
Hi @Aditi574 
I was working on the new merged code which should show sorted results. 
Here is what I have found.

image
**"Bogo Sort"** 



image
**"C Topic"**


I have just attached 2 Screenshots
You can try the query 'graph' and you will find 'Adjacency Lists In C' down somewhere in the end even if it starts with 'A'. 

I am not sure if the results are sorting as expected.
@AdiChat correct me if I am wrong.
If I have misunderstood the feature.

**Comment by AasthaGupta** [comment]
@AnkitaKhurana Thank you for pointing this out.
The reason for some of the results not getting sorted was that we were sorting results on the basis of 'keys' but keys are also contain multiple other search queries.

@AdiChat I have fixed it here #69

**Pull request merged**
