### PR TITLE
Removed unnecessary console log

### PR DESCRIPTION
**Pull request by Aditi574**
**Fixes issue:**

**Changes:**

There was an unnecessary console.log() line which will be removed by this patch.

### CODE REVIEW

**Comment by Aditi574** [comment]
@AdiChat Please review it.

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by Aditi574** [comment]
@AdiChat yes I'm enjoying it. My teammate @AasthaGupta and I, as part of team DevGals, are looking forward to making contributions to OpenGenus as part of RGSoC'18 :)

**Comment by AdiChat** [comment]
Great. We hope to see you at RGSoC. :smile:

**Pull request merged**
