### PR TITLE
flappy bird game added

### PR DESCRIPTION
**Pull request by aryabharat**
**Fixes issue:**

**Changes:**

### CODE REVIEW

**Comment by AnkitaKhurana** [comment]
Just a suggestion, breaking the flappy_bird.js code into components might make the code more cleaner and easy to understand. Great job on the game implementation!

**Comment by aryabharat** [comment]
Components like different files for different web components?

**Comment by AnkitaKhurana** [comment]
Yes. The individual objects can be separated (Bird | Messages |Score), etc.

**Comment by aryabharat** [comment]
Done it pls check!

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**
og_j

**Pull request merged**
