### PR TITLE
Share feature added

### PR DESCRIPTION
**Pull request by dimi-23**
**Fixes issue:**

#93 

**Changes:**

The feature of sharing the extension to Facebook, Twitter, Google+ and LinkedIn has been added below the tags as shown:
image

After clicking on the icons, the following pages get opened:

Facebook:
image

Twitter:
image

Google+:
image

LinkedIn:
image

@AdiChat kindly review the changes made.

### CODE REVIEW

**Comment by richa208** [comment]
Hi @dimi-23 
I had mentioned [here](https://github.com/OpenGenus/quark/issues/93) previously that I am working on this issue. Due to some other prior engagements I was not able to submit a PR for it till now. But I had spent much of my time on this issue and have got the solution for it also.
share
@AdiChat Kindly resolve this conflict

**Comment by dimi-23** [comment]
Hi @richa208, I completely agree with your point but when work is not assigned to anyone it is more of an Open issue.
Kindly look at this one for example: https://github.com/OpenGenus/quark/issues/34

Also, I was very curious to work on this issue thereby I finished the work the same day as the issue was raised but I waited for 2 days for the issue to be assigned to someone, after which I decided to raise my Pull Request on understanding that it was an Open issue.
I think our focus should be on the overall development of the project we are working on in a good spirit, without wasting our time on such petty issues.

**Comment by AdiChat** [comment]
Both of you are wonderful contributors :heart:  and have taken Quark to the next level. Do not let this conflict impact our community. :family_man_woman_girl_boy: 

We, usually, do not assign issues as it might keep new contributors away to join the discussion. It is based on the understanding between contributors. From this incident, we understand that contributors should communicate a timeline in which they expect to complete milestones, mention that he/she would be trying it and others. In short, we must strengthen our communication. 

As both of you have made pull requests, we will merge both with slight modifications. :muscle: 

@dimi-23 You may use a sharing message such as "#OpenGenus Quark: World's first offline search engine to enable you to learn offline [link]". 

@richa208 You may place the sharing icons in the help modal in a sequence. This will be a minor change. 

Ideally, we must keep the same images considering memory constraints. As both sets of images are beautiful, you may keep it as it is for the moment. Hopefully, this conflict will not reduce the enjoyment derived from developing Quark. 

Happy journey with OpenGenus :smile:

**Comment by dimi-23** [comment]
Hi @AdiChat! Thank you for such a generous response! 💛 
I've updated the sharing message to the one mentioned by you!

**Comment by AdiChat** [comment]
Looks great 😍 

Hope you are enjoying your journey 🚆  with **OpenGenus**

**Pull request merged**
