### PR TITLE
Number of searches displayed

### PR DESCRIPTION
**Pull request by richa208**
**Fixes issue:**

#7 

**Changes:**

After every search query, the total number of results found will be displayed.

### CODE REVIEW

**Comment by AdiChat** [comment]
It works great. 👍 

In case of `0` results, you may not display this message as we have a custom page for it. 

Additionally, you may take a look at the style for this information in [Cosmos Search](http://search.opengenus.org/query/?q=linear+search) and try to adapt to something similar or better. 👍

**Comment by AdiChat** [comment]
Looks great 😍 

I fixed the size to reduce the emphasis on this detail (which was tending to divert attention from the results to this detail) 
Hope you are enjoying your journey 🚆  with **OpenGenus**

**Comment by richa208** [comment]
Thanks.. and sorry for the mistake :sweat_smile:

**Comment by AdiChat** [comment]
No problem 👍

**Pull request merged**
